# Generated by Django 5.0.3 on 2024-05-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_author_alter_book_book_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_img',
            field=models.URLField(null=True),
        ),
    ]
