# Generated by Django 5.0.3 on 2024-05-07 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_book_img'),
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='book_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book'),
        ),
    ]
